version: '3'
services:
  client:
    build:
      context: ./news-forum
    ports:
      - "3000:3000"

  server:
    build:
      context: ./my-backend
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    volumes:
      - ./my-backend:/app
